export default {
  "zh-CN":"简体中文",
  "zh-TW":"正體中文",
  "en":"English",
  "es":"Español",
  "pt":"Português",
  "ru":"Русский",
  "ja":"日本語",
  "ach":"Acoli",
  "af":"Afrikaans",
  "ak":"Akan",
  "ay":"Aymara",
  "az":"azərbaycan",
  "ban":"Balinese",
  "su":"Basa Sunda",
  "bho":"Bhojpuri",
  "ceb":"Binisaya",
  "x-bork":"Bork, bork, bork!",
  "bs":"bosanski",
  "br":"brezhoneg",
  "ca":"català",
  "cs":"Čeština",
  "sn":"chiShona",
  "co":"Corsican",
  "cy":"Cymraeg",
  "da":"Dansk",
  "de":"Deutsch",
  "yo":"Èdè Yorùbá",
  "et":"eesti",
  "eo":"esperanto",
  "eu":"euskara",
  "ee":"Eʋegbe",
  "x-elmer":"Ewmew Fudd",
  "fil":"Filipino",
  "fo":"føroyskt",
  "fr":"Français",
  "fy":"Frysk",
  "gaa":"Ga",
  "ga":"Gaeilge",
  "gd":"Gàidhlig",
  "gl":"galego",
  "gn":"Guarani",
  "ht":"Haitian Creole",
  "ha":"Hausa",
  "hr":"Hrvatski",
  "haw":"ʻŌlelo Hawaiʻi",
  "bem":"Ichibemba",
  "ig":"Igbo",
  "rn":"Ikirundi",
  "id":"Indonesia",
  "ia":"interlingua",
  "xh":"isiXhosa",
  "zu":"isiZulu",
  "is":"íslenska",
  "it":"Italiano",
  "jv":"Jawa",
  "rw":"Kinyarwanda",
  "sw":"Kiswahili",
  "tlh":"Klingon",
  "kg":"Kongo",
  "mfe":"kreol morisien",
  "kri":"Krio",
  "ku":"kurdî",
  "la":"Latin",
  "lv":"latviešu",
  "to":"lea fakatonga",
  "lt":"lietuvių",
  "ln":"lingála",
  "loz":"Lozi",
  "lua":"Luba-Lulua",
  "lg":"Luganda",
  "hu":"magyar",
  "mg":"Malagasy",
  "mt":"Malti",
  "ms":"Melayu",
  "pcm":"Naijíriá Píjin",
  "nl":"Nederlands",
  "no":"norsk",
  "nn":"norsk nynorsk",
  "nso":"Northern Sotho",
  "ny":"Nyanja",
  "uz":"o‘zbek",
  "oc":"Occitan",
  "om":"Oromoo",
  "x-pirate":"Pirate",
  "pl":"polski",
  "ro":"română",
  "rm":"rumantsch",
  "qu":"Runasimi",
  "nyn":"Runyankore",
  "crs":"Seselwa Creole French",
  "sq":"shqip",
  "sk":"Slovenčina",
  "sl":"slovenščina",
  "so":"Soomaali",
  "st":"Southern Sotho",
  "sr-Latn":"srpski (latinica)",
  "fi":"Suomi",
  "sv":"Svenska",
  "mi":"te reo Māori",
  "vi":"Tiếng Việt",
  "tn":"Tswana",
  "tum":"Tumbuka",
  "tr":"Türkçe",
  "tk":"türkmen dili",
  "wo":"Wolof",
  "el":"Ελληνικά",
  "be":"беларуская",
  "bg":"български",
  "ky":"кыргызча",
  "kk":"қазақ тілі",
  "mk":"македонски",
  "mn":"монгол",
  "sr":"српски",
  "tt":"татар",
  "tg":"тоҷикӣ",
  "uk":"Українська",
  "ka":"ქართული",
  "hy":"հայերեն",
  "yi":"ייִדיש",
  "iw":"עברית",
  "ug":"ئۇيغۇرچە",
  "ur":"اردو",
  "ar":"العربية",
  "ps":"پښتو",
  "sd":"سنڌي",
  "fa":"فارسی",
  "ckb":"کوردیی ناوەندی",
  "ti":"ትግር",
  "am":"አማርኛ",
  "ne":"नेपाली",
  "mr":"मराठी",
  "sa":"संस्कृत भाषा",
  "hi":"हिन्दी",
  "as":"অসমীয়া",
  "bn":"বাংলা",
  "pa":"ਪੰਜਾਬੀ",
  "gu":"ગુજરાતી",
  "or":"ଓଡ଼ିଆ",
  "ta":"தமிழ்",
  "te":"తెలుగు",
  "kn":"ಕನ್ನಡ",
  "ml":"മലയാളം",
  "si":"සිංහල",
  "th":"ไทย",
  "lo":"ລາວ",
  "my":"မြန်မာ",
  "km":"ខ្មែរ",
  "chr":"ᏣᎳᎩ",
  "ko":"한국어"
}
